-- ========================================================
-- LoveWeb Complete Database Schema for Supabase
-- Run this script in your Supabase Dashboard -> SQL Editor
-- ========================================================

-- ১. User_Information টেবিল তৈরি (ব্যবহারকারীর মূল অ্যাকাউন্ট তথ্য)
CREATE TABLE IF NOT EXISTS public."User_Information" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT NOT NULL,
    password TEXT NOT NULL
);

-- কলামগুলোর দ্রুত সার্চিংয়ের জন্য ইনডেক্স
CREATE INDEX IF NOT EXISTS idx_user_info_username ON public."User_Information" (username);
CREATE INDEX IF NOT EXISTS idx_user_info_email ON public."User_Information" (email);
CREATE INDEX IF NOT EXISTS idx_user_info_phone ON public."User_Information" (phone);

-- ২. Password_Resets টেবিল তৈরি (ওটিপি ও পাসওয়ার্ড/ইমেইল রিসেট তথ্য)
CREATE TABLE IF NOT EXISTS public."Password_Resets" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    email TEXT NOT NULL,
    otp_code TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

-- ওটিপি খোঁজার জন্য ইনডেক্স
CREATE INDEX IF NOT EXISTS idx_password_resets_email_otp ON public."Password_Resets" (email, otp_code);
CREATE INDEX IF NOT EXISTS idx_password_resets_expires ON public."Password_Resets" (expires_at);

-- ========================================================
-- ৩. Row Level Security (RLS) ও অ্যাক্সেস পলিসি কনফিগারেশন
-- (এটি ছাড়া ফ্রন্টএন্ড থেকে ডেটা ইনসার্ট/রিড/আপডেট কাজ করবে না)
-- ========================================================

-- User_Information RLS
ALTER TABLE public."User_Information" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon select User_Information" ON public."User_Information";
CREATE POLICY "Allow anon select User_Information" 
ON public."User_Information" FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow anon insert User_Information" ON public."User_Information";
CREATE POLICY "Allow anon insert User_Information" 
ON public."User_Information" FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update User_Information" ON public."User_Information";
CREATE POLICY "Allow anon update User_Information" 
ON public."User_Information" FOR UPDATE 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon delete User_Information" ON public."User_Information";
CREATE POLICY "Allow anon delete User_Information" 
ON public."User_Information" FOR DELETE 
TO anon, authenticated 
USING (true);

-- Password_Resets RLS
ALTER TABLE public."Password_Resets" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon select Password_Resets" ON public."Password_Resets";
CREATE POLICY "Allow anon select Password_Resets" 
ON public."Password_Resets" FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow anon insert Password_Resets" ON public."Password_Resets";
CREATE POLICY "Allow anon insert Password_Resets" 
ON public."Password_Resets" FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon delete Password_Resets" ON public."Password_Resets";
CREATE POLICY "Allow anon delete Password_Resets" 
ON public."Password_Resets" FOR DELETE 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow anon update Password_Resets" ON public."Password_Resets";
CREATE POLICY "Allow anon update Password_Resets" 
ON public."Password_Resets" FOR UPDATE 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);
