const fs = require('fs');

let langCode = fs.readFileSync('js/language.js', 'utf8');

const missingTranslations = `
  // Nav and Side Menu
  "অফিশিয়াল প্ল্যাটফর্ম": "Official Platform",
  "অর্ডার বিস্তারিত": "Order Details",
  "অ্যাকাউন্ট থেকে লগআউট": "Logout from Account",
  "অ্যাকাউন্ট সেটিংস": "Account Settings",
  "আপনি কি নিশ্চিত যে আপনার LoveWeb অ্যাকাউন্ট থেকে লগআউট করতে চান?": "Are you sure you want to logout of your LoveWeb account?",
  "আমাদের কাজের নমুনা দেখুন": "View our work samples",
  "উইশিং অর্ডারের স্ট্যাটাস ও হিস্ট্রি": "Wishing order status & history",
  "গোপনীয়তা ও নিয়মাবলী": "Privacy & Rules",
  "ডেমো গ্যালারি": "Demo Gallery",
  "থিম মোড": "Theme Mode",
  "নতুন উইশিং ওয়েবসাইট তৈরি করুন": "Create a new wishing website",
  "পলিসি ও সিকিউরিটি গাইডলাইন": "Policy & Security Guidelines",
  "পাসওয়ার্ড ও ইমেইল পরিবর্তন": "Change Password & Email",
  "প্রধান মেন্যু": "Main Menu",
  "ব্যক্তিগত তথ্য ও নিরাপত্তা": "Personal Info & Security",
  "ব্যবহারকারী প্রোফাইল": "User Profile",
  "ব্যবহারবিধি ও সাধারণ প্রশ্নোত্তর": "Usage & FAQs",
  "মেসেঞ্জারে সরাসরি যোগাযোগ": "Direct Contact on Messenger",
  "লগআউট করুন": "Log Out",
  "লগইন / সাইন আপ": "Login / Sign Up",
  "লাইভ চ্যাট সাপোর্ট": "Live Chat Support",
  "সহায়তা ও তথ্য": "Help & Information",
  "সাহায্য কেন্দ্র (FAQ)": "Help Center (FAQ)",
  "হোম": "Home",
  "হোম ও প্রধান সেবা": "Home & Main Services",
  "ডার্ক মোড": "Dark Mode",
  "লাইট মোড": "Light Mode",

  // Privacy and Rules
  "গোপনীয়তা নীতি ও ব্যবহারের নিয়মাবলী": "Privacy Policy & Terms of Use",
  "গোপনীয়তা নীতি ও ব্যবহারের শর্তাবলী - LoveWeb": "Privacy Policy & Terms of Use - LoveWeb",
  "সর্বশেষ হালনাগাদ: সেপ্টেম্বর ২০২৬": "Last Updated: September 2026",
  "LoveWeb ব্যবহারের পূর্বে আমাদের সুরক্ষা ও ব্যবহারের নির্দেশিকাগুলো অনুগ্রহ করে পড়ে নিন": "Please read our security and usage guidelines before using LoveWeb",
  "অ্যাকাউন্ট তথ্য:": "Account Information:",
  "আপনার প্রিয়জনের নাম, ছবি, ভিডিও, অডিও ও বিশেষ শুভেচ্ছা বার্তা।": "Your loved one's name, photos, videos, audio, and special wishing messages.",
  "আপনি চাইলে যেকোনো সময় আপনার আপলোডকৃত ছবি বা সম্পূর্ণ উইশিং ওয়েবসাইট মুছে ফেলার অনুরোধ করতে পারেন।": "You can request to delete your uploaded photos or the entire wishing website at any time.",
  "উইশিং পেজ কন্টেন্ট:": "Wishing Page Content:",
  "এই ওটিপি কোড কখনো কারও সাথে শেয়ার করবেন না।": "Never share this OTP code with anyone.",
  "একটি কুপন কোড একটি নির্দিষ্ট সময় বা নির্দিষ্ট সংখ্যক ব্যবহারের জন্য কার্যকর থাকে।": "A coupon code is valid for a specific period or a limited number of uses.",
  "একবার নির্দিষ্ট অর্ডারের শর্ত পূরণ হলে এই মেম্বারশিপ স্ট্যাটাস ও ডিসকাউন্ট সুবিধা আজীবন সচল থাকবে এবং প্রতিটি অর্ডারে সরাসরি প্রযোজ্য হবে।": "Once the required order criteria are met, this membership status and discount will remain active for life and apply directly to every order.",
  "এলিট মেম্বার (Elite Member):": "Elite Member:",
  "ও প্রায়োরিটি ডেলিভারি সুবিধা পাবেন।": "and receive priority delivery.",
  "কারো অনুমতি ছাড়া তার ছবি দিয়ে মানহানিকর, অশ্লীল বা বিভ্রান্তিকর কন্টেন্ট তৈরি করা।": "Creating defamatory, obscene, or misleading content using someone's photo without permission.",
  "কুপনের মাধ্যমে প্রাপ্ত ডিসকাউন্ট আপনার অর্ডারের মোট মূল্যে সমন্বয় করা হবে এবং এটি অ্যাডমিন প্যানেল দ্বারা সংরক্ষিত থাকবে।": "The discount received via coupon will be adjusted against your total order value and securely recorded by the admin panel.",
  "কোনো ব্যবহারকারীর ব্যক্তিগত কন্টেন্ট কখনো আমাদের বিজ্ঞাপন, প্রমোশন বা জনসাধারণের কোনো গ্যালারিতে ব্যবহার করা হবে না।": "No user's personal content will ever be used in our advertisements, promotions, or public galleries.",
  "ধর্মীয় অনুভূতিতে আঘাত হানে এমন বার্তা বা রাজনৈতিক বিদ্বেষ ছড়ানো।": "Spreading messages that hurt religious sentiments or political hatred.",
  "পাসওয়ার্ড রিসেটের ক্ষেত্রে প্রেরিত ওটিপি (OTP) কোড নির্দিষ্ট সময়ের জন্য কার্যকর থাকে।": "For password resets, the sent OTP code is valid for a limited time.",
  "পাসওয়ার্ড সম্পূর্ণ এনক্রিপ্টেড আকারে ডাটাবেসে সংরক্ষিত থাকে যা LoveWeb-এর কর্তৃপক্ষের কাছেও পাঠযোগ্য নয়।": "Passwords are stored in the database in a fully encrypted format, completely unreadable even to LoveWeb authorities.",
  "পাসওয়ার্ডের এনক্রিপ্টেড হ্যাশ ও ওটিপি ভেরিফিকেশন লগ।": "Encrypted password hashes and OTP verification logs.",
  "প্রদান করা হয়।": "is provided.",
  "প্রিমিয়াম মেম্বার (Premium Member):": "Premium Member:",
  "ব্যবহারকারীকে নিজস্ব অ্যাকাউন্ট নিরাপদ রাখতে শক্তিশালী পাসওয়ার্ড ব্যবহারের পরামর্শ দেওয়া হয়।": "Users are advised to use a strong password to keep their accounts secure.",
  "ব্যবহারকারীর আপলোডকৃত ব্যক্তিগত ছবি, ভিডিও কিংবা বার্তা কেবল সংশ্লিষ্ট উইশিং ওয়েবসাইটের জন্যই ব্যবহৃত হয়।": "The user's uploaded personal photos, videos, or messages are used exclusively for the respective wishing website.",
  "ব্যবহারকারীর পুরো নাম, ইউজারনেম, ইমেইল অ্যাড্রেস এবং ফোন নম্বর।": "User's full name, username, email address, and phone number.",
  "ভুল বা মেয়াদ উত্তীর্ণ কুপনের ক্ষেত্রে ডিসকাউন্ট প্রযোজ্য হবে না।": "Discounts will not apply for invalid or expired coupons.",
  "ভেরিফাইড ফেসবুক পেজে": "Verified Facebook Page",
  "লগইন ক্রেডেনশিয়াল:": "Login Credentials:",
  "সাধারণ সদস্য (Normal Member):": "Normal Member:",
  "স্প্যামিং, ফিশিং বা কোনো প্রকার সাইবার অপরাধমূলক কার্যকলাপ।": "Spamming, phishing, or any form of cyber-criminal activities.",
  "আজীবন মেম্বারশিপ স্ট্যাটাস:": "Lifetime Membership Status:",
  "অফিশিয়াল কুপন কোডগুলো কেবল আমাদের": "Official coupon codes are strictly available on our",
  "উপভোগ করবেন।": "enjoy.",

  // Help page
  "সাহায্য ও FAQ": "Help & FAQ",
  "সহায়তা ও সাধারণ প্রশ্নোত্তর (FAQ)": "Help & Frequently Asked Questions (FAQ)",
  "সাহায্য ও প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী (FAQ) - LoveWeb": "Help & Frequently Asked Questions (FAQ) - LoveWeb",
  "LoveWeb কী এবং এটি কীভাবে কাজ করে?": "What is LoveWeb and how does it work?",
  "উইশিং ওয়েবসাইট কীভাবে তৈরি করা যায়?": "How can I create a wishing website?",
  "এলিট ও প্রিমিয়াম মেম্বারশিপ কী এবং এটি কীভাবে পাওয়া যায়?": "What are Elite and Premium Memberships and how do I get them?",
  "এলিট ও প্রিমিয়াম মেম্বারশিপে কী কী ডিসকাউন্ট ও সুবিধা পাওয়া যায়?": "What discounts and benefits do Elite and Premium memberships offer?",
  "কুপন কোড কোথায় পাবো এবং কিভাবে ব্যবহার করবো?": "Where can I find coupon codes and how do I use them?",
  "তৈরিকৃত লিংক কতদিন পর্যন্ত সক্রিয় থাকে?": "How long does a created link stay active?",
  "পাসওয়ার্ড ভুলে গেলে কীভাবে উদ্ধার করব?": "How do I recover my password if I forget it?",
  "সরাসরি যোগাযোগ ও সহায়তা পাওয়ার উপায় কী?": "What are the ways to contact and get direct support?",
  "এই মেম্বারশিপ ডিসকাউন্ট আজীবন সচল থাকে এবং কোনো কুপন কোড ছাড়াই চেকআউটের সময় স্বয়ংক্রিয়ভাবে সমন্বিত হয়।": "This membership discount remains active for life and is automatically applied at checkout without any coupon code.",
  "এলিট মেম্বারদের জন্য:": "For Elite Members:",
  "ও প্রায়োরিটি এক্সপ্রেস কাস্টমাইজেশন সেবা।": "and priority express customization service.",
  "পরবর্তী প্রতিটি অর্ডারে নিশ্চিত": "Guaranteed on every subsequent order",
  "পাসওয়ার্ড রিসেট পাতায়": "On the Password Reset page",
  "প্রতিটি অর্ডারে সর্বোচ্চ": "Maximum on every order",
  "প্রশ্নে ক্লিক করলে নিচে স্ক্রল হয়ে বিস্তারিত উত্তর দেখতে পাবেন": "Click on a question to scroll down and see the detailed answer",
  "প্রিমিয়াম মেম্বারদের জন্য:": "For Premium Members:",
  "ফেসবুক পেজে": "Facebook Page",
  "(বিঃদ্রঃ ওটিপি যদি ইনবক্সে না পান, তবে আপনার ইমেইলের Spam ফোল্ডার চেক করুন)": "(Note: If you don't receive the OTP in your inbox, check your email's Spam folder)",
  "যান। সেখানে আপনার নিবন্ধিত ইমেইল প্রদান করলে আপনার ইমেইলে একটি ৬-সংখ্যার ওটিপি (OTP) কোড পাঠানো হবে।": "Enter your registered email, and a 6-digit OTP code will be sent to your email.",
  "শুনছে... কথা বলুন": "Listening... Speak now",
  "১,০০০ টাকার নিচে অর্ডার সম্পন্নকারী গ্রাহকগণ।": "Customers with orders below ৳1,000.",
  "৪% (4%) স্পেশাল ডিসকাউন্ট": "4% Special Discount",
  "৮% (8%) এক্সক্লুসিভ ডিসকাউন্ট": "8% Exclusive Discount",
  "৪% (4%) বিশেষ ডিসকাউন্ট": "4% Special Discount",
  "৮% (8%) এক্সক্লুসিভ ডিসকাউন্ট": "8% Exclusive Discount",
  "গোপনীয়তা ও শর্তাবলী": "Privacy & Terms",
  "অথবা স্ক্রিনের নিচের ডান কোণায় থাকা মেসেঞ্জার আইকনে ক্লিক করে সরাসরি আমাদের মেসেঞ্জার পেজে": "Or click the Messenger icon in the bottom right corner of the screen to directly visit our Messenger page",
`;

const targetInsert = '"লগইন করুন": "Log Into Your World",';

if (langCode.includes(targetInsert) && !langCode.includes('"অফিশিয়াল প্ল্যাটফর্ম"')) {
    langCode = langCode.replace(targetInsert, missingTranslations + "\n  " + targetInsert);
    fs.writeFileSync('js/language.js', langCode);
    console.log("Added missing translations to language.js");
}
